### ISSUE TITLE
Dependency on lzma-native fails.

### ISSUE THREAD

**Issue by ilg-ul** [kevva/decompress-tarxz#10]
Please note that currently lzma-native fails to install on node 9.x, and consequently decompress-tarxz, a nice package otherwise, cannot be used. :-(

https://github.com/addaleax/lzma-native/issues/55

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/decompress-tarxz/commit/5ce2d3bef9f1d017780863f4bcbe53931c788373. Install `v3.0.0`.

**Comment by ilg-ul** [comment]
ok, thank you.
